version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: ./auth
    container_name: auth_service
    ports:
      - "4001:4001"
    networks:
      - my_network
    environment:
      MONGODB_URI: mongodb://my_mongodb:27017/auth-db
    depends_on:
      - mongodb

  event-service:
    build:
      context: ./event
    container_name: event_service
    ports:
      - "4002:4002"
    networks:
      - my_network
    environment:
      MONGODB_URI: mongodb://my_mongodb:27017/event-db
    depends_on:
      - mongodb

  gateway-service:
    build:
      context: ./gateway
    container_name: gateway_service
    ports:
      - "4000:4000"
    networks:
      - my_network
    depends_on:
      - auth-service
      - event-service

networks:
  my_network:

volumes:
  mongo_data:
